# run: conda env create -n <name> --file environment.yml
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10.4
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - pytorch::torchaudio=0.12.1
  - cudatoolkit=11.3.1
  # - pytorch-cuda=11.6
  - pip
  - pip:
      - pillow==9.0.1
      - transformers==4.16.2
      - sentencepiece==0.1.96
      - typer==0.4.1
